name: Python CI

on:
  push:
    branches:
      - main  # Replace with your main branch name if different
  pull_request:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
